# Generated by Django 4.2.6 on 2023-10-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='bloque',
            field=models.BooleanField(default=False),
        ),
    ]
