# Generated by Django 4.1 on 2023-10-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='joined_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employe',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
    ]
