# Generated by Django 4.2.6 on 2023-10-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=60)),
                ('dateBorrow', models.DateField(null=True)),
                ('available', models.BooleanField()),
                ('borrower', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Cd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=60)),
                ('dateBorrow', models.DateField()),
                ('available', models.BooleanField()),
                ('borrower', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Dvd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('realisator', models.CharField(max_length=60)),
                ('dateBorrow', models.DateField()),
                ('available', models.BooleanField()),
                ('borrower', models.CharField(max_length=60)),
            ],
        ),
    ]
