# Generated by Django 4.1 on 2023-11-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mediatheque_root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cd',
            name='dateBorrow',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='dateBorrow',
            field=models.DateField(null=True),
        ),
    ]
