# Generated by Django 4.2.6 on 2023-11-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mediatheque_root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cd',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
